# Generated by Django 4.2.1 on 2023-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('R', 'Ready'), ('C', 'Charging'), ('W', 'Waiting'), ('E', 'Error')], default='R', max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
